---
title: '[20170607]重讀者，2017，誰是新世代？全國大學詩社座談會觀察'
author: "Nobuusa"
date: "2017年6月7日"
output: html_notebook
---
### **壹、背景**
#### **一、原因：網路衝擊了實體詩社（大學詩社）**
***
* 網路詩平臺的崛起

    * 時間：1995年。

    * 描述：寫詩者利用網路（BBS站台、網路新聞台、部落格以及論壇）傳播和實驗詩。

* 網路詩人的發跡

    * 例子：「風球詩人」、「逗點詩人」、「好燙詩人」、「衛生紙詩人」。

    * 手段：出刊或結社。

    * 效果：網路詩人成為「詩壇新生代」的代名詞。

* 「大學詩社」的特徵

    * 向網路尋找資源`（強的網路詩人）`
    * 抱怨大學詩社內新手與行政雜務

* 提問：傳統的詩社形式跟不上網路時代，所以失去吸引力了嗎？

#### **二、結果：網路詩人的崛起**
***
* 主旨：`（「網路詩人」？）`，獲得主流詩壇的承認。

* 組成：七年級青年詩人（被稱為新生代勢力）。

* 手段：以「新生代」為名收獲更多關注、七年級詩人亦高手雲集。

* 效果：對八年級學生為主的大學詩社造成經營上的壓力。

* 特徵：善於利用網路交流、善於結盟。

#### **【本段閱讀疑問】**

***
  1. 長期單打獨鬥的詩人（「網路詩人」？）
  1. 本段未交代清楚：`七年級、八年級、大學詩社、跨校詩社、新生代、網路詩人`之間的關係

### **貳、本文案例：詩社會議**
***
#### **一、詩社集會、集會模式與效果**
***
* 流程
    1. 自我介紹
    1. 各詩社「一社對一社，一次十分鐘」深度對談。

* 效果
    1. 促進彼此的認識
    1. 社團的現況與合作
    1. 會後以地緣關係或者彼此的交往程度形成了幾個集群。

#### **二、大學詩社（社團特徵分析）運作特徵**
***
* **Type-01**

    * 活動：讀詩會跟喝酒。
 
    * 費用：講義印刷。
 
* **Type-02**

    * 目標：吸引關注。
 
    * 手段：加入其他文學類別。
 
* **Type-03**

    * 目標：成為正式社團。
 
* **Type-04**

    * 困境：學校沒有中文系、缺乏校方主辦的文學獎、缺乏文學活動、地處偏遠。
 
    * 結果：招生困難、困擾授課詩人。
 
* **Type-05**

    * 手段：一學期三堂詩人講座、現代詩與現代舞結合。

* **Type-06**

    * 手段：集中製作社刊、金車現代詩講座提供金援和資源。

#### **三、大學詩社的總問題**
***
* 困難：
    * ~~詩的困難~~
    * **社團經營的困難**`（社團經營、教學資源（的尋找與互助）招生策略）`
        * 社會因素：「讀什麼科系、以後就從事相關行業」的觀念，導致犧牲個人興趣培養的學生、家長、學校存在。
        * 詩社屬性
            * 以詩藝磨練為目的的社團（菁英取向）；
            * 現代詩推廣，促進閱讀人口的社團（大眾取向）；
            * 以詩為口號，讓大家都聚集在一起的同好會
        * 財源（看得到拿不到）
            * 大學社團評鑑的經費
                * 問題：部分大學不歧視靜態活動，利於詩社以評鑑爭取學校經費資源，部分則否。
                * 障礙：評鑑要求社團的組織健康度，高比例的服務學習分數。
                * 結果：詩社造成負擔，必須投入資源但不確定回報。
            * 社費
                * 問題：詩社難以訂出合適的社費。
        * 支出
            * 問題：文學講師授課費用偏高。
            * 原因：
                1. 學校的補助過少
                1. 人力和社費無法擴增
            * 效應：減少新進社員的入社意願。
                * 風險：人員變動（e.g.,擔任要職的幹部轉學或畢業），行政交接與教學上的斷層。
        * 缺乏切磋來源
            * 障礙：臉書時代，缺乏新詩的切磋資源（過去依賴e.g.,葡萄海論壇、吹鼓吹詩論壇、ptt詩版）。
            * 對策：
                1. 內部讀詩會為原則，
                1. 跨校讀詩會為例外。
            * 益：內部的詩學見解靠近
            * 損：閉門造車。

#### **四、總對策**
***
* 經營方針改變
    * ~~紙本刊物~~
    * **「資源共享」與「社群經營」**

* 對策：私密的臉書社團（星系進化論）作為發展重心。

* 問題
    * 人力資源（有品質評論者）的很難無條件持續運作
    * 社團間的交流讓社團被同化，失去特殊性

* 結論
    1. 大學詩社難維持動力、持續交流；
    1. 跨詩社的臉書社團成為廣告張貼處。

* 建議：利用粉絲專頁、讀詩專頁，推廣活動並行銷自己。

### **參、結語：座談會尾聲**
***
* 結論：未達到共識，但詩社更認識彼此。

### **肆、這篇文章的啟發**
***
* 組織定位決定資源投入，那麼，組織該如何定位？

    * 精益求精
    
    * 推廣
    
    * 同樂會
    
→這三種類型，資源配置和消耗狀況不同

* 組織該如何確定定位？

    * 運作型（收支為主）
    
        * 量入為出？（能拿多少錢再決定發展成哪種類型？）
        
        * 量出為入？（先決定發展成哪種類型，再找錢？）
        
    * 意志型（組織成員的目標為主）
    
        * 多數決？（大家想幹甚麼）
        
        * 少數決？（首長、幹部群想幹甚麼）
        
* 小結
    顯然，組織運作得顧及物質資源多寡、環境狀況，否則，組織設立無法執行成功的目標，是無法續存，但是，目標設定若不顧意志與信念，組織成員也沒動機積極付出，因為這不是期待的回報。
